### PR TITLE
Fix/moved mag reset outside of constructor

### LINKED ISSUE #32: icm20948 reset_mag() function contains logic bug
hal::write(*m_i2c, ak09916_address, std::array<hal::byte, 2>{ ak09916_cntl_3, 0x01 }, hal::never_timeout()); // Soft

The line above has an issue do to what I think talking to the mag directly and can only be done in bypass mode.

### PR DESCRIPTION
**Pull request by yyaatt0**
I removed the reset_mag() call inside the icm constructor because after a icm reset, the i2c master may not be ready. For a reliable and consistent startup of the icm device, reseting the mag outside of the constructor consistently works. Also included the reset_mag() call in the demo file as an example of how to use the driver. 

Note: I have tried polling until the i2c master is ready, but still did not work. 

Resolves #32

### CODE REVIEW

**Review by kammce — CHANGES_REQUESTED** [review]
Thank you so much for the PR. from reviewing this, I think I see what's needed. You brought out the logic for resetting and initializing the driver on the outside so you could control how much time elapses before each step. What this tells me is that the constructor for the driver actually needs a `steady_clock` passed into it so it can delay the necessary amount of time. Otherwise, we put the burden on the developer using this driver:

1. To remember to initialize these in the right order
2. To delay the right amount between messages. 

So what we should do is add that new constructor that takes a steady clock by reference and put a `[[deprecated(message)]]` attribute on the old constructor. That way people get a warning to not use it since it's dangerous.

Thank you again for taking this on.

**Comment by yyaatt0** [comment]
I've added the depreciated attribute to the old constructor as well as passing steady clock into the icm. I also needed to add helper functions to help allow time and ensure i2c is ready during the reset calls; specifically mag_whoami_ok() and reset_i2c_master().

If there are any critiques, let me know and I'll update accordingly.

File: include/libhal-sensor/imu/icm20948.hpp [hunk 1]
```diff
@@ -312,10 +326,14 @@ class icm20948
   void enable_mag_data_read(hal::byte p_reg, hal::byte p_bytes);
 
   void reset_icm20948();
+  void reset_i2c_master();
 
   /* The I2C peripheral used for communication with the device. */
   hal::i2c* m_i2c;
 
+  /* The Clock peripheral is used to provide delay until I2C master is ready. */
+  hal::steady_clock* m_steady_clock;
```
Comment (kammce) [inline include/libhal-sensor/imu/icm20948.hpp]: Do we need the steady clock after initialization? If not, then there is no need for us to hold the steady clock as a member.

File: src/imu/icm20948.cpp [hunk 2]
```diff
@@ -661,4 +710,26 @@ void icm20948::enable_mag_data_read(hal::byte p_reg,   // NOLINT
...
+{
+  try {
+    enable_bypass_mode();
+
+    auto const wia1 = whoami_ak09916_wia1_direct();
+    auto const wia2 = whoami_ak09916_wia2_direct();
+
+    return (wia1 == static_cast<hal::byte>(ak09916_who_am_i_1)) &&
+           (wia2 == static_cast<hal::byte>(ak09916_who_am_i_2));
+  } catch (std::exception const&) {
```
Comment (kammce) [inline src/imu/icm20948.cpp]: This exception is a bit too broad. I assume this exception is for the `hal::no_such_device`. We don't normally catch `std::exception`.

**Review by kammce — CHANGES_REQUESTED** [review]

File: src/imu/icm20948.cpp (hunk 2 above)
Comment (yyaatt0) [reply src/imu/icm20948.cpp]: would it be better to do a safe throw instead ? similar to this snippet of code in the constructor? 

if (auto id = whoami(); id != who_am_i_content) {
    hal::safe_throw(hal::no_such_device(id, this));
  }
  
  Edit: to clarify, adding a safe throw inside the catch block for example

Comment (kammce) [reply src/imu/icm20948.cpp]: I was referencing the catch statement. You should catch `hal::no_such_device`. You shouldn't catch `std::exception`

**Review by kammce — APPROVED** [review]

File: src/imu/icm20948.cpp (hunk 2 above)
Comment (kammce) [reply src/imu/icm20948.cpp]: Looks like you made the change, so i'll resolve this

**Comment by kammce** [comment]
Going to merge this now as we have things to fix on the CI side for sensor.
